#include "..\headers\define.h"
//---------------------

#define NAME                            SCRIPT_MCRdrBld
#define TOWN_REP_VAR                    GVAR_TOWN_REP_RAIDERS // привязка к репутации (-1, если не нужно)
#define BOX_TILE                        10  // номер тайла с личным товарным ящиком (-1, если не надо; не использовать значения от 1 до 10; не может совпадать с чужими ящиками на одной локации)

#define NUM_TEAM                        TEAM_WAR_ROADS        // группа, к которой принадлежит персонаж (-1 если нужно оставить Team, заданный в редакторе)
#define NUM_AI                          AI_WAR_ROAD           // AI персонажа (-1 если нужно оставить AI, заданный в редакторе)
#define KILL_SLAVA                      SLAVA_KILL_BAD        // слава за убийство этого персонажа (SLAVA_KILL_GOOD, SLAVA_KILL_BAD, SLAVA_KILL_NEITRAL, SLAVA_KILL_CHILD)
#define KILL_TOWN_REP                   REP_KILL_CRITICAL     // репутация за убийство этого персонажа (REP_KILL_GOOD, REP_KILL_BAD, REP_KILL_NEITRAL, REP_KILL_CRITICAL для враждебности всего поселения, REP_KILL_CHILD)
#define KILL_FRAC_REP                   FRAC_WARROAD          // принадлежность определенной фракции (-1, если не нужно)

#define FLAG_STEAL                      20  // Нижний порог навыка для кражи (для торговцев 200, для животных 300)
#define FLAG_ALCOHOL                    0  // Примет ли алкоголь от ГГ: 0 - принимает, 1 - не принимает
#define FLAG_FOOD                       0  // Примет ли пищу от ГГ: 0 - принимает, 1 - не принимает

//---------------------

procedure start;
procedure map_enter_p_proc;
procedure setBarterA;
procedure setBarterB;
procedure map_update_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure timed_event_p_proc;
procedure critter_p_proc;
procedure use_obj_on_p_proc;
procedure use_skill_on_p_proc;
procedure uninjure_proc;
procedure pickup_p_proc;
procedure combat_p_proc;
procedure damage_p_proc;
procedure destroy_p_proc;
procedure talk_p_proc;

procedure Node998;
procedure Node999;
procedure NodeStartDialog;
procedure NodeFstDialog;
procedure NodeSndDialog;
procedure NodeAnswer100;
procedure NodeAnswer101;
procedure NodeAnswer102;
procedure NodeAnswer103;
procedure NodeAnswer104;

//---------------------

//#define LVAR_Flag_A                     (6) // отвечает за ...

//---------------------



procedure start begin
end

procedure map_enter_p_proc begin
   if (is_loading_game == false) then begin
       set_start_home
       set_BarterBoxProc(ONE_GAME_WEEK)
       set_injure_start(0,1,0,0,0) // травмировать (отметить нужное цифрой 1): a - левая рука, b - правая рука, c - левая нога, d - правая нога, e - слепота
   end
end

procedure setBarterA begin
   //! пока пусто
end

procedure setBarterB begin
        check_restock_item(PID_W_GRENADE_MOLOTOV, 4, 6, 100)
        check_restock_item(PID_AMMO_TANK, 4, 5, 100) // в пачке 5 шт
   set_BarterDopusk;
end

procedure map_update_p_proc begin
   set_injure_update(120,103)
end

procedure look_at_p_proc begin
   lookProcMsg
end

procedure description_p_proc begin
   //dsrptProcMsg
   script_overrides;
   if (get_Medic_Quest == 0) then begin
   display_mstr(101);
   end
   else begin
   display_mstr(102);
   end
end

procedure timed_event_p_proc begin
   // Таймер за номером 1 зарезервирован под перемещение персонажа по локации
   // Таймер за номером 2 зарезервирован под всплывающие реплики
   if (fixed_param == 1) then begin
       timer_move_to_home
   end
   if (fixed_param == 2) then begin
       //timer_float_reply(120,121)
   end
   if (fixed_param == 3) then begin
       KillScorpTail(-1)
   end
end

procedure critter_p_proc begin
   set_critter_options(0,0) //условие нападения (0 личная вражда, 1 вражда клановая, 2 всегда), разворот к ГГ
end

procedure use_skill_on_p_proc begin
   skillUseSteal
   skillUseFAid
   skillUseDoctor(65)
end

procedure uninjure_proc begin
   //не удалять
   set_REP(2)
end

procedure pickup_p_proc begin
   pickupProcCritter
end

procedure use_obj_on_p_proc begin
   UsedItemToCrit_Proc
   UsedToCrit_Stimpak_Doctor
   UsedToCrit_Scorp(106,3) // фраза над жертвой (-1 если не нужна), номер таймера
end

procedure combat_p_proc begin
   effectAttak(0,0,1,1,1) //отравление min, облучение min, травма ног %, травма рук %, травма глаз %
end

procedure damage_p_proc begin
   set_damage_dude
end

procedure destroy_p_proc begin
   if (source_obj == dude_obj) then begin
   set_map_var(MVAR_CAR_PRESENT,0);
   set_map_var(MVAR_ROADWAR_DOPUSK,-1);
   end
   kill_critter_opt
   kill_critter_box
end

procedure talk_p_proc begin
   if town_rep_is_vilified then begin
   floater(self_obj,108,COLOR_MSG_RED);
   end
   else if (get_Medic_Quest == 0) then begin
   floater(self_obj,104,COLOR_MSG_NORMAL);
   end
   else begin
   //floater(self_obj,105,COLOR_MSG_NORMAL);
   setReaction(-1) // Отношение к ГГ(1 - персонаж положительный, -1 отрицательный, 0 нейтральный)
   fracReaction(GVAR_TITUL_ARIZONA_RANGER,-20) // Поправка к отношению за принадлежность к фракциям
   fracReaction(GVAR_TITUL_WARRIOR_ROAD,70) // Поправка к отношению за принадлежность к фракциям
   dialog_proc_barter(1,104,NodeStartDialog,-1,-1)
   end
end

procedure Node998 begin
   setNodeCombat;
end

procedure Node999 begin
end

procedure NodeStartDialog begin
   if (bitDialog(bit_1) == 0) then begin
   call NodeFstDialog;
   end
   else begin
   call NodeSndDialog;
   end
end

//--- ПЕРВЫЙ ДИАЛОГ

procedure NodeFstDialog begin
   bitDialogExp(bit_1,0)
   Reply(200)
   NAnswer(201,1,NodeSndDialog)
end

//--- ПОВТОРНЫЙ ДИАЛОГ

procedure NodeSndDialog begin
   Reply(210)
   /*
   Изготавливает и продаёт топливо для огнемета и огненные бомбы.
   	- Принеси мне горючих материалов, я всё организую. / Разве у вас не целый бак топлива? / Топливо в этом баке выдаёт Бен только для дела. Не думаю, что он даст тебе его просто так.
   */
   NAnswer(220,1,NodeAnswer100)
   NAnswer(222,1,NodeAnswer101)
   NAnswer(224,1,NodeAnswer102)
   NAnswer(211,1,Node999)
end

procedure NodeAnswer100 begin
   Reply(221)
   NAnswer(222,1,NodeAnswer101)
   NAnswer(224,1,NodeAnswer102)
   NAnswer(211,1,Node999)
end

procedure NodeAnswer101 begin
   Reply(223)
   NAnswer(220,1,NodeAnswer100)
   NAnswer(224,1,NodeAnswer102)
   NAnswer(211,1,Node999)
end

procedure NodeAnswer102 begin
   Reply(225)
   if (get_BarterDopusk == 0) then begin
   NAnswer(226,1,NodeAnswer103)
   end
   NAnswer(220,1,NodeAnswer100)
   NAnswer(222,1,NodeAnswer101)
   NAnswer(211,1,Node999)
end

procedure NodeAnswer103 begin
   Reply(227)
   NAnswer(228,1,NodeAnswer104)
   NAnswer(220,1,NodeAnswer100)
   NAnswer(222,1,NodeAnswer101)
   NAnswer(211,1,Node999)
end

procedure NodeAnswer104 begin
   call setBarterB;
   goBarterMod;
   call NodeSndDialog;
end
