#include "..\headers\define.h"
#include "..\headers\REPAIR.h"
#define NAME                            SCRIPT_CSWrkTb
#define SKILL_LIMIT                     0

procedure start;
procedure map_enter_p_proc;
procedure use_skill_on_p_proc;
procedure use_obj_on_p_proc;



procedure start begin
end

procedure map_enter_p_proc begin
end

procedure use_skill_on_p_proc begin
end

procedure use_obj_on_p_proc begin
   stopUseCarGaz
   else RepairProcUsingMexTorpedos
end
