#include "..\headers\define.h"
#define NAME                            SCRIPT_RSQrzStr

procedure start;
procedure map_enter_p_proc;
procedure map_update_p_proc;



procedure start begin
end

procedure map_enter_p_proc begin
end

procedure map_update_p_proc begin
   if (gvar_bit(GVAR_DIALOGS_FLAGS_BIT, bit_3) == 0) then begin
   set_obj_visibility(self_obj, 1);
   end
   else begin
   set_obj_visibility(self_obj, 0);
   end
end
