#include "..\headers\define.h"
#define NAME                    SCRIPT_RTDeads

procedure start;
procedure spatial_p_proc;



procedure start begin
end

procedure spatial_p_proc begin
   if (source_obj == dude_obj) then begin
      if (global_var(GVAR_RANGERS_AQUEDUCT_BODIES) == 0) then begin
      display_mstr(100);
      floater(source_obj,101,COLOR_MSG_NORMAL);
      reg_anim_clear(source_obj);
      inc_global_var(GVAR_RANGERS_AQUEDUCT_BODIES);
      end
   end
end
