#include "..\headers\define.h"
#define NAME                    SCRIPT_PVTExp

procedure start;
procedure spatial_p_proc;



procedure start begin
end

procedure spatial_p_proc begin
   if (source_obj == dude_obj) then begin
       if (getQuest(GVAR_VAULT25_VISITED) < qEnd) then begin
           reg_anim_clear(source_obj);
           exp_add_msg(1000,NAME,100,101);
           setQuest(GVAR_VAULT25_VISITED,qEnd);
       end
   end
end
