#include "..\headers\define.h"
#define NAME                    SCRIPT_VSBabStr

procedure start;
procedure use_p_proc;



procedure start begin
end

procedure use_p_proc begin
   if (map_var(MVAR_VILLA_BabaDialog) == 0) then begin
   script_overrides;
   reg_anim_begin();
   reg_anim_clear(self_obj);
   reg_anim_clear(source_obj);
   reg_anim_end();
   display_mstr(110);
   floater(dude_obj,111,COLOR_MSG_NORMAL);
   end
end
