#include "..\headers\define.h"
#define NAME                    SCRIPT_VSDstr

procedure start;
procedure map_enter_p_proc;
procedure use_obj_on_p_proc;



procedure start begin
end

procedure map_enter_p_proc begin
   if (is_loading_game == false) then begin
      if (getQuest(GVAR_MAIN_QUEST_TWOSUN) >= qEnd) then begin
      set_obj_visibility(self_obj, 1);
      end
   end
end

procedure use_obj_on_p_proc begin
   stopUseCarGaz
end
