#include "..\headers\define.h"
#define NAME                    SCRIPT_EncComix

procedure start;
procedure use_p_proc;

variable skillNum;



procedure start begin
end

procedure use_p_proc begin
   gfade_out(ONE_GAME_SECOND);
    game_time_advance(ONE_GAME_HOUR);
   gfade_in(ONE_GAME_SECOND);
   skillNum := random(SKILL_SMALL_GUNS, SKILL_SCOUT);
   skill_up(skillNum,5);
   display_mstr(100);
   scr_return(1);
end
