#include "..\headers\define.h"
#define NAME                    SCRIPT_EncLmnt3

procedure start;
procedure map_enter_p_proc;
procedure map_update_p_proc;



procedure start begin
end

procedure map_enter_p_proc begin
   if (is_loading_game == false) then begin
      if (map_first_run) then begin
      set_obj_visibility(self_obj, 1);
      end
   end
end

procedure map_update_p_proc begin
   if (map_var(MVAR_ENC_CRY_STATUS)>=3) then begin
   set_obj_visibility(self_obj, 0);
   end
end
