#include "..\headers\define.h"
#define NAME                            SCRIPT_DSBndInv

procedure start;
procedure map_enter_p_proc;
procedure use_obj_on_p_proc;



procedure start begin
end

procedure map_enter_p_proc begin
   set_obj_visibility(self_obj, 1);
   if (getQuest(GVAR_CGRANDE_QST_BANDITS) != qZero) then begin
   set_obj_visibility(self_obj, 0);
   end
end

procedure use_obj_on_p_proc begin
   stopUseCarGaz
end
