#include "..\headers\define.h"
#define NAME                            SCRIPT_PIMapPnx

procedure start;
procedure use_p_proc;



procedure start begin
end

procedure use_p_proc begin
   script_overrides;
   mark_world_subtile_visited(850, 600, 2);
      mark_on_map(AREA_PHOENIX)
      mark_on_map(AREA_SAN_BRAHMIN)
      mark_on_map(AREA_CASA_GRANDE)
   exp_add(100);
   skill_up(SKILL_SCOUT,5);
   scr_return(1);
end
