#ifndef CRITRPID_H
#define CRITRPID_H

#define PID_HERO_PRIMITIVE_MALE         (16777217)
#define PID_HERO_PRIMITIVE_FEMALE       (16777218)
#define PID_PRIMITIVE_VILLAGER_MALE     (16777219)
#define PID_PRIMITIVE_VILLAGER_FEMALE   (16777220)
#define PID_ANT                         (16777221)
#define PID_ANT_GUARD                   (16777222)
#define PID_ANT_GLOW                    (16777223)
#define PID_MANTIS                      (16777224)
#define PID_MANTIS_GIGANT               (16777225)
#define PID_MANTIS_MATHER               (16777226)
#define PID_RAT                         (16777227)
#define PID_RAT_CITY                    (16777228)
#define PID_RAT_PIG                     (16777229)
#define PID_RAT_MOLE                    (16777230)
#define PID_RAT_GOD                     (16777231)
#define PID_COYOTE                      (16777232)
#define PID_DOG                         (16777233)
#define PID_DOG_KING                    (16777234)
#define PID_WOLF                        (16777235)
#define PID_SCORPION_SMALL              (16777236)
#define PID_SCORPION_BIG                (16777237)
#define PID_SCORPION_LEGEND             (16777238)
#define PID_BRAHMIN_CARAVAN             (16777239)
#define PID_BRAHMIN_HOME                (16777240)
#define PID_BRAHMIN_WILD                (16777241)
#define PID_BRAHMIN_LOW                 (16777242)
#define PID_PLANT                       (16777243)
#define PID_FLOATER                     (16777244)
#define PID_CENTOUR                     (16777245)
#define PID_EL_MONSTRO                  (16777246)
#define PID_EL_GIGANTO                  (16777247)
#define PID_EL_DIABLO                   (16777248)
#define PID_MR_HANDY                    (16777249)
#define PID_ROBOBRAIN                   (16777250)
#define PID_ROBOT_EYEBALL               (16777251)
#define PID_ROBOT_ARMY                  (16777252)
#define PID_ROBOT_TURREL                (16777253)
#define PID_GHOUL_A                     (16777254)
#define PID_GHOUL_B                     (16777255)
#define PID_GHOUL_LOW                   (16777256)
#define PID_GHOUL_RIPPER                (16777257)
#define PID_GHOUL_GLOW                  (16777258)
#define PID_GHOUL_SPORONOS              (16777259)
#define PID_GHOST                       (16777260) // призрак из убежища 27
#define PID_CHILD_MALE                  (16777261)
#define PID_CHILD_FEMALE                (16777262)
#define PID_SAVAGE_MALE                 (16777263) // дикарь
#define PID_SAVAGE_FEMALE               (16777264) // дикарка
#define PID_PEASANT_MALE                (16777265) // крестьянин в желтой рубахе
#define PID_PEASANT_FEMALE              (16777266) // крестьянка
#define PID_CITIZEN_A_MALE              (16777267) // лошина М
#define PID_CITIZEN_A_FEMALE            (16777268) // лошина Ж
#define PID_CITIZEN_B_MALE              (16777269) // горожанин-негр
#define PID_CITIZEN_B_FEMALE            (16777270) // горожанка
#define PID_CITIZEN_C_MALE              (16777271) // горожанин в зеленой рубахе
#define PID_CITIZEN_C_FEMALE            (16777272) // горожанка
#define PID_DEALER_MALE                 (16777273) // торговец
#define PID_DEALER_FEMALE               (16777274) // торговка
#define PID_MERCHANT_MALE               (16777275) // торговец-купец
#define PID_MERCHANT_FEMALE             (16777276) // торговка-купец
#define PID_MERC_A_MALE                 (16777277) // кожанка М
#define PID_MERC_A_FEMALE               (16777278) // кожанка Ж
#define PID_MERC_B_MALE                 (16777279) // кожанка и синие штаны М
#define PID_MERC_B_FEMALE               (16777280) // кожанка Ж с ирокезом
#define PID_MERC_C_MALE                 (16777281) // кожаная броня М
#define PID_MERC_C_FEMALE               (16777282) // кожаная броня Ж
#define PID_MERC_D_MALE                 (16777283) // металброня М
#define PID_MERC_D_FEMALE               (16777284) // металброня Ж
#define PID_MERC_E_MALE                 (16777285) // боевая броня М
#define PID_MERC_E_FEMALE               (16777286) // боевая броня М
#define PID_RANGER_MALE                 (16777287) // рейнджер М
#define PID_RANGER_FEMALE               (16777288) // рейнджер Ж
#define PID_RANGER_VETERAN              (16777289) // рейнджер-ветеран
#define PID_RANGER_GENERAL              (16777290) // генерал-рейнджер
#define PID_BOS_SCRIBE_MALE             (16777291) // писарь М
#define PID_BOS_SCRIBE_FEMALE           (16777292) // писарь Ж
#define PID_BOS_SCOUT                   (16777293) // разведчик
#define PID_BOS_CAVALER                 (16777294) // рыцарь
#define PID_BOS_PALADIN                 (16777295) // паладин в силовой броне
#define PID_BOS_PALADIN_LEADER          (16777296) // верховный паладин
#define PID_CULT_FIRE_MISSIONER         (16777297)
#define PID_CULT_FIRE                   (16777298)
#define PID_PHENIX_BOSS                 (16777299)
#define PID_SCIENTIST                   (16777300)
#define PID_CULT_APOCALIPSIS_MALE       (16777301)
#define PID_CULT_APOCALIPSIS_FEMALE     (16777302)
#define PID_TINNER                      (16777303)
#define PID_TINNER_TUCH                 (16777304)
#define PID_TINNER_LEADER               (16777305)
#define PID_PRIESTESS                   (16777306)
#define PID_PUDRE                       (16777307)
#define PID_BABA                        (16777308)
#define PID_PASTOR                      (16777309)
#define PID_MYST_STRANGER               (16777310)
#define PID_MSTR_KOGAN                  (16777311)
#define PID_ADMIN                       (16777312)
#define PID_FABER                       (16777313)
#define PID_ARTUR                       (16777314)
#define PID_GHOST_OWSR                  (16777315)
#define PID_PHNX_OWSR                   (16777316) // 100
#define PID_DON_DIEGO                   (16777317) // 101
#define PID_MIGEL                       (16777318) // 102
#define PID_ANJELO                      (16777319) // 103
#define PID_BOXER                       (16777320) // 104
#define PID_BOXER_A                     (16777321) // 105
#define PID_BOXER_B                     (16777322) // 106
#define PID_BOXER_C                     (16777323) // 107
#define PID_BOXER_D                     (16777324) // 108
#define PID_CITIZEN_D_MALE              (16777325) // 109
#define PID_CITIZEN_D_FEMALE            (16777326) // 110
#define PID_GENERAL_SARABIA             (16777327) // 111
#define PID_RED_RYDER                   (16777328) // 112
#define PID_ROAD_BOSS                   (16777329) // 113
#define PID_PALADIN_BIRKLY              (16777330) // 114
#define PID_MASTER                      (16777331) // 115
#define PID_SUPERMUTANT                 (16777332) // 116
#define PID_GHOST_MALE                  (16777333) // 117
#define PID_GHOST_FEMALE                (16777334) // 118
#define PID_EL_GARRA                    (16777338) // 122

//--- FID персонажей
#define FID_NAROBE                      (16777247)   // отшельник
#define FID_NMBRLP                      (16777256)   // горожанин в желтой одежде
#define FID_NMPEAS                      (16777264)   // горожанин в кепке (как Дантоны в Кламате)
#define FID_NMWARR                      (16777280)   // дикарь М
#define FID_NWVALT                      (16777290)   // жительница убежища, без номера на спине

#endif
