#ifndef TEAMS_H
#define TEAMS_H

//--- Главный герой и его напарники

#define TEAM_PLAYER                              (0) // ГГ собственной персоной

//--- Живность

#define TEAM_ANT                                 (1) // муравьи
#define TEAM_MANTIS                              (2) // мантисы
#define TEAM_RATS                                (3) // крысы, кротокрысы, свинокрысы, крысиный король
#define TEAM_DOG                                 (4) // собаки, волки, койоты
#define TEAM_SCORPION                            (5) // радскорпионы
#define TEAM_BRAHMIN                             (6) // брамины
#define TEAM_SPORE_PLANT                         (7) // хищные растения
#define TEAM_DEATHCLAW                           (8) // когти смерти
#define TEAM_ROBOTS                              (9) // роботы
#define TEAM_GHOUL_WILD                         (10) // дикий гуль

//--- Типовые нпс

#define TEAM_CARAVAN                            (20) // типовой караван
#define TEAM_BANDITS                            (21) // типовые бандиты и грабители
#define TEAM_RAIDERS                            (22) // типовые рейдеры
#define TEAM_MERKENARY                          (23) // типовые охотники за головами, наемники
#define TEAM_TRAPPERS                           (75) // типовые охотники
#define TEAM_SAVAGE                             (31) // типовые дикари (включая Шакалов на их локации, дикарей на карте мира, рыбаков на полуострове)

//--- Жители локаций

#define TEAM_VILLA_PEASAN                       (30) // житель Виллы
#define TEAM_JACKALS_PEASAN                     (TEAM_SAVAGE) // члены племени Шакалов
#define TEAM_GARAGE_CITIZEN                     (32) // житель Гаража
#define TEAM_GARAGE_CLAN_A                      (70) // клан 1 в Гараже
#define TEAM_GARAGE_CLAN_B                      (71) // клан 2 в Гараже
#define TEAM_SANBRAHMIN_PEASAN                  (33) // житель СанБрамин
#define TEAM_FLAGSTAFF_CITIZEN                  (34) // житель Флагпула
#define TEAM_PHOENIX_CITIZEN                    (35) // житель Феникса
#define TEAM_TWOSUN_PEASAN                      (36) // жители и жестянщики ТуСана
#define TEAM_TWOSUN_SLAVES                      (68) // беглые рабы ТуСана
#define TEAM_CASAGRANDE_PEASAN                  (37) // житель КасаГранде
#define TEAM_CASAGRANDE_CITYHALL                (74) // мэрия КасаГранде
#define TEAM_CASANUEVA_PEASAN                   (38) // житель КасаНуэвa
#define TEAM_MOTEL_MUTANT                       (39) // мутанты Мотеля
#define TEAM_VAULT_GHOST                        (40) // призраки убежища 27
#define TEAM_INFERNO_CULT                       (41) // разумные гули Инферно
#define TEAM_INFERNO_GHOUL                      (42) // дикие гули Инферно (не актуально)

//--- Фракции

#define TEAM_FLAGSTAFF_MERC                     (50) // наемники Флагпула
#define TEAM_FLAGSTAFF_SLAVES                   (51) // рабы Флагпула
#define TEAM_RANGERS                            (52) // рейнджеры
#define TEAM_BROTHERS_STEEL                     (53) // член Братства Стали
#define TEAM_CULT_ATOMIC                        (54) // член культа Огня
#define TEAM_WAR_ROADS                          (55) // магистральщики
#define TEAM_HERMO_FORT                         (73) // гарнизон Эрмосильо

//--- Локальные группы Феникса

#define TEAM_PHOENIX_JUNK                       (60) // нищеброды
#define TEAM_PHOENIX_PIMP                       (61) // пушеры
#define TEAM_PHOENIX_COLLECTOR                  (62) // повстанцы
#define TEAM_PHOENIX_PLANT                      (63) // атомщики АЭС
#define TEAM_PHOENIX_CASINO                     (64) // казино
#define TEAM_PHOENIX_RING                       (65) // бойцы ринга
#define TEAM_PHOENIX_EXPERIMENT                 (66) // подопытные в убежище 25
#define TEAM_PHOENIX_BANDIT                     (67) // уличные бандиты
#define TEAM_PHOENIX_MERC                       (72) // наемники Феникса (гильдия охотников за головами)

#endif
